export const equipmentSlots = [
  { id: 'head', label: 'Head' },
  { id: 'face', label: 'Face' },
  { id: 'body', label: 'Body' },
  { id: 'back', label: 'Back' },
  { id: 'mainHand', label: 'Main Hand' },
  { id: 'offHand', label: 'Off Hand' },
  { id: 'feet', label: 'Feet' },
  { id: 'trinket', label: 'Trinket' },
];

export const bearCharacters = [
  {
    id: 'bruno',
    name: 'Bruno Bear',
    classPath: 'storm_guardian',
    role: 'Front-line guardian',
    storyHook: 'Bruno protects Honeywood Plaza when Ranger Magnus opens the storm gates.',
    baseStats: { courage: 9, speed: 5, magic: 4, crafting: 3, drone: 2 },
    starterEquipment: {
      head: 'storm_cap',
      body: 'honeywood_coat',
      mainHand: 'honey_hammer',
      offHand: 'family_badge',
      back: 'adventurer_pack',
    },
    powers: ['storm_paw', 'family_rally'],
  },
  {
    id: 'memi',
    name: 'Memi Bear',
    classPath: 'sun_honey_mage',
    role: 'Ranged support',
    storyHook: 'Memi turns festival honey into sunlight magic that clears dark vines.',
    baseStats: { courage: 6, speed: 6, magic: 9, crafting: 5, drone: 4 },
    starterEquipment: {
      head: 'sunflower_hat',
      body: 'festival_cloak',
      mainHand: 'sun_honey_wand',
      offHand: 'picnic_lantern',
      trinket: 'sun_honey_charm',
    },
    powers: ['sun_honey_burst', 'moon_shield'],
  },
  {
    id: 'mumma',
    name: 'Mumma Bear',
    classPath: 'forest_protector',
    role: 'Shield and control',
    storyHook: 'Mumma awakens ancient forest roots to protect Cubby and the picnic trail.',
    baseStats: { courage: 7, speed: 4, magic: 7, crafting: 9, drone: 3 },
    starterEquipment: {
      head: 'leaf_crown',
      body: 'guardian_apron',
      mainHand: 'forest_shield',
      offHand: 'root_lantern',
      feet: 'moss_boots',
    },
    powers: ['root_guardian', 'family_rally'],
  },
  {
    id: 'papa',
    name: 'Papa Bear',
    classPath: 'forge_captain',
    role: 'Builder and heavy striker',
    storyHook: 'Papa rebuilds bridges, powers workshops, and keeps the Honey Drone flying.',
    baseStats: { courage: 8, speed: 4, magic: 3, crafting: 10, drone: 8 },
    starterEquipment: {
      head: 'forge_cap',
      body: 'builder_vest',
      mainHand: 'forge_gauntlet',
      offHand: 'drone_remote',
      back: 'drone_pack',
    },
    powers: ['forge_roar', 'drone_pulse'],
  },
  {
    id: 'cubby',
    name: 'Cubby Bear',
    classPath: 'picnic_scout',
    role: 'Agile scout',
    storyHook: 'Cubby starts as the rescue mission, then becomes the fastest explorer in Honeywood.',
    unlock: 'Complete Chapter 2 rescue quest',
    baseStats: { courage: 5, speed: 10, magic: 5, crafting: 4, drone: 6 },
    starterEquipment: {
      head: 'cub_scout_cap',
      body: 'tiny_adventure_jacket',
      mainHand: 'berry_slinger',
      offHand: 'small_picnic_basket',
      feet: 'river_sneakers',
    },
    powers: ['berry_cyclone', 'drone_pulse'],
  },
];

export const equipmentCatalog = [
  {
    id: 'honey_hammer',
    slot: 'mainHand',
    family: 'hammer',
    name: 'Honey Hammer',
    rarity: 'starter',
    modifiers: { courage: 2 },
    kidSafeEffect: 'Stuns enemies with a sticky honey thump.',
  },
  {
    id: 'berry_bow',
    slot: 'mainHand',
    family: 'bow',
    name: 'Berry Bow',
    rarity: 'rare',
    modifiers: { speed: 1, courage: 1 },
    kidSafeEffect: 'Launches berry shots that make enemies dizzy.',
  },
  {
    id: 'sun_honey_wand',
    slot: 'mainHand',
    family: 'wand',
    name: 'Sun Honey Wand',
    rarity: 'starter',
    modifiers: { magic: 2 },
    kidSafeEffect: 'Casts bright honey light to clear dark magic.',
  },
  {
    id: 'forest_shield',
    slot: 'mainHand',
    family: 'shield',
    name: 'Forest Shield',
    rarity: 'starter',
    modifiers: { courage: 1, crafting: 1 },
    kidSafeEffect: 'Raises roots that block trouble safely.',
  },
  {
    id: 'drone_remote',
    slot: 'offHand',
    family: 'tech',
    name: 'Honey Drone Remote',
    rarity: 'epic',
    modifiers: { drone: 3 },
    kidSafeEffect: 'Calls the Honey Drone for scanning, shielding, and stun pulses.',
  },
  {
    id: 'storm_cap',
    slot: 'head',
    family: 'cap',
    name: 'Storm Cap',
    rarity: 'starter',
    modifiers: { courage: 1 },
    kidSafeEffect: 'Crackles with tiny cartoon lightning.',
  },
  {
    id: 'drone_pack',
    slot: 'back',
    family: 'pack',
    name: 'Drone Pack',
    rarity: 'epic',
    modifiers: { drone: 2, crafting: 1 },
    kidSafeEffect: 'Stores drone batteries and rescue tools.',
  },
];

export const powerCatalog = [
  {
    id: 'storm_paw',
    name: 'Storm Paw',
    type: 'stun',
    cooldownMs: 6500,
    range: 2,
    ownerPaths: ['storm_guardian'],
    effect: 'Thunder stun and knockback.',
  },
  {
    id: 'sun_honey_burst',
    name: 'Sun Honey Burst',
    type: 'area_support',
    cooldownMs: 8000,
    range: 4,
    ownerPaths: ['sun_honey_mage'],
    effect: 'Bright area burst that clears hazards.',
  },
  {
    id: 'root_guardian',
    name: 'Root Guardian',
    type: 'trap',
    cooldownMs: 9000,
    range: 3,
    ownerPaths: ['forest_protector'],
    effect: 'Root trap that safely holds enemies.',
  },
  {
    id: 'forge_roar',
    name: 'Forge Roar',
    type: 'buff',
    cooldownMs: 10000,
    range: 5,
    ownerPaths: ['forge_captain'],
    effect: 'Team courage and crafting boost.',
  },
  {
    id: 'drone_pulse',
    name: 'Drone Pulse',
    type: 'tech_stun',
    cooldownMs: 7500,
    range: 6,
    ownerPaths: ['forge_captain', 'picnic_scout'],
    effect: 'Disables ranger machines and signal towers.',
  },
  {
    id: 'family_rally',
    name: 'Family Rally',
    type: 'team_buff',
    cooldownMs: 15000,
    range: 6,
    ownerPaths: ['storm_guardian', 'forest_protector'],
    effect: 'Boosts nearby family and bot companions.',
  },
];
